package com.example.myapplication.Client

import com.example.myapplication.R
import kotlin.random.Random

// ESTRUCTURA DE DATOS FINAL Y CORRECTA
data class PrestadorProfileFalso(
    val id: String,
    val name: String,
    val lastName: String,
    val profileImageUrl: Any?,
    val bannerImageUrl: Any?,
    val rating: Float,
    val services: List<String>,
    val companyName: String? = null,
    val address: String,
    val email: String,
    val doesHomeVisits: Boolean,
    val hasPhysicalLocation: Boolean,
    val works24h: Boolean,
    val galleryImages: List<String>,
    val isFavorite: Boolean = false,
    val isVerified: Boolean,
    val isOnline: Boolean,
    val isSubscribed: Boolean // CAMPO IS_SUBSCRIBED RE-AÑADIDO
)

object SampleDataFalso {

    val prestadores = listOf(
        PrestadorProfileFalso(
            id = "1",
            name = "Maxi",
            lastName = "Nanterne",
            profileImageUrl = R.drawable.maverickprofile,
            bannerImageUrl = R.drawable.myeasteregg,
            rating = 100f,
            isVerified = true,
            isOnline = true,
            services = listOf("Informatica", "Electricidad", "Reparación", "Camaras de Seguridad"),
            companyName = "Maverick Informatica",
            address = "B. Matienzo 1339",
            email = "informaticamaverick@gmail.com",
            doesHomeVisits = true,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf("https://example.com/gallery1_1.jpg", "https://example.com/gallery1_2.jpg"),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "2",
            name = "María",
            lastName = "García",
            profileImageUrl = "https://picsum.photos/seed/2/200/200",
            bannerImageUrl = "https://picsum.photos/seed/2_banner/800/400",
            rating = 4.5f,
            isVerified = true,
            isOnline = false,
            services = listOf("Limpieza", "Jardinería", "Cuidado de Plantas"),
            address = "Calle Falsa 123",
            email = "maria.garcia@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = true,
            galleryImages = listOf("https://picsum.photos/seed/2_gallery/400/300"),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "3",
            name = "Carlos",
            lastName = "Rodriguez",
            profileImageUrl = "https://picsum.photos/seed/3/200/200",
            bannerImageUrl = "https://picsum.photos/seed/3_banner/800/400",
            rating = 4.2f,
            isVerified = false,
            isOnline = true,
            services = listOf("Carpintería", "Reparación de Muebles", "Ensamblaje de Muebles"),
            address = "Boulevard de los Sueños Rotos 45",
            email = "carlos.r@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/3_gallery/400/300"),
            isFavorite = false,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "4",
            name = "Ana",
            lastName = "Martinez",
            profileImageUrl = "https://picsum.photos/seed/4/200/200",
            bannerImageUrl = "https://picsum.photos/seed/4_banner/800/400",
            rating = 4.9f,
            isVerified = true,
            isOnline = true,
            services = listOf("Diseño", "Marketing Digital", "Redacción", "Programador"),
            companyName = "Creativos Digitales",
            address = "Plaza de la Tecnología 101",
            email = "ana.m@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = true,
            galleryImages = listOf("https://picsum.photos/seed/4_gallery1/400/300", "https://picsum.photos/seed/4_gallery2/400/300"),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "5",
            name = "Luis",
            lastName = "Hernández",
            profileImageUrl = "https://picsum.photos/seed/5/200/200",
            bannerImageUrl = "https://picsum.photos/seed/5_banner/800/400",
            rating = 3.8f,
            isVerified = false,
            isOnline = false,
            services = listOf("Mecánica", "Lavado de Autos"),
            address = "Calle de los mecánicos 78",
            email = "luis.h@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = false,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "6",
            name = "Sofia",
            lastName = "Lopez",
            profileImageUrl = "https://picsum.photos/seed/6/200/200",
            bannerImageUrl = "https://picsum.photos/seed/6_banner/800/400",
            rating = 5.0f,
            isVerified = true,
            isOnline = true,
            services = listOf("Repostería", "Catering", "Cocina"),
            companyName = "Dulce Sofía",
            address = "Avenida del Sabor 33",
            email = "sofia.l@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/6_gallery/400/300"),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "7",
            name = "Javier",
            lastName = "Gomez",
            profileImageUrl = "https://picsum.photos/seed/7/200/200",
            bannerImageUrl = "https://picsum.photos/seed/7_banner/800/400",
            rating = 4.0f,
            isVerified = true,
            isOnline = false,
            services = listOf("Fotografía", "Edición de Video", "Animación"),
            address = "Calle del Recuerdo 18",
            email = "javier.g@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/7_gallery/400/300"),
            isFavorite = false,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "8",
            name = "Laura",
            lastName = "Diaz",
            profileImageUrl = "https://picsum.photos/seed/8/200/200",
            bannerImageUrl = "https://picsum.photos/seed/8_banner/800/400",
            rating = 4.6f,
            isVerified = true,
            isOnline = true,
            services = listOf("Cuidado de Niños", "Tutorías", "Cuidado de Ancianos"),
            address = "Rincón Infantil 99",
            email = "laura.d@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = true,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "9",
            name = "David",
            lastName = "Moreno",
            profileImageUrl = "https://picsum.photos/seed/9/200/200",
            bannerImageUrl = "https://picsum.photos/seed/9_banner/800/400",
            rating = 4.3f,
            isVerified = false,
            isOnline = true,
            services = listOf("Desarrollo Web", "Programador", "Tecnología"),
            companyName = "Soluciones Web DM",
            address = "Avenida Digital 404",
            email = "david.m@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = true,
            galleryImages = listOf("https://picsum.photos/seed/9_gallery/400/300"),
            isFavorite = false,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "10",
            name = "Carmen",
            lastName = "Jimenez",
            profileImageUrl = "https://picsum.photos/seed/10/200/200",
            bannerImageUrl = "https://picsum.photos/seed/10_banner/800/400",
            rating = 4.8f,
            isVerified = true,
            isOnline = false,
            services = listOf("Entrenamiento Personal", "Nutrición", "Clases de Yoga"),
            address = "Gimnasio Fuerte 10",
            email = "carmen.j@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "11",
            name = "Pedro",
            lastName = "Alvarez",
            profileImageUrl = "https://picsum.photos/seed/11/200/200",
            bannerImageUrl = "https://picsum.photos/seed/11_banner/800/400",
            rating = 4.1f,
            isVerified = false,
            isOnline = true,
            services = listOf("Mudanzas", "Ensamblaje de Muebles"),
            address = "Calle del Transporte 321",
            email = "pedro.a@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = true,
            galleryImages = listOf(),
            isFavorite = false,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "12",
            name = "Isabel",
            lastName = "Romero",
            profileImageUrl = "https://picsum.photos/seed/12/200/200",
            bannerImageUrl = "https://picsum.photos/seed/12_banner/800/400",
            rating = 4.7f,
            isVerified = true,
            isOnline = true,
            services = listOf("Belleza", "Peluqueria", "Sastrería"),
            address = "Salón de Belleza Bella",
            email = "isabel.r@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/12_gallery/400/300"),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "13",
            name = "Francisco",
            lastName = "Santos",
            profileImageUrl = "https://picsum.photos/seed/13/200/200",
            bannerImageUrl = "https://picsum.photos/seed/13_banner/800/400",
            rating = 4.4f,
            isVerified = true,
            isOnline = false,
            services = listOf("Jardinería", "Diseño de Interiores", "Cuidado de Plantas"),
            companyName = "Verde Vida",
            address = "Camino de las Flores 15",
            email = "francisco.s@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/13_gallery/400/300"),
            isFavorite = false,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "14",
            name = "Elena",
            lastName = "Torres",
            profileImageUrl = "https://picsum.photos/seed/14/200/200",
            bannerImageUrl = "https://picsum.photos/seed/14_banner/800/400",
            rating = 4.9f,
            isVerified = true,
            isOnline = true,
            services = listOf("Asesoría Legal", "Contabilidad", "Abogado"),
            companyName = "Soluciones Legales y Contables",
            address = "Avenida de la Justicia 88",
            email = "elena.t@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = true,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "15",
            name = "Miguel",
            lastName = "Ramirez",
            profileImageUrl = "https://picsum.photos/seed/15/200/200",
            bannerImageUrl = "https://picsum.photos/seed/15_banner/800/400",
            rating = 3.9f,
            isVerified = false,
            isOnline = false,
            services = listOf("Cerrajería", "Seguridad"),
            address = "Calle de la Seguridad 247",
            email = "miguel.r@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = true,
            galleryImages = listOf(),
            isFavorite = false,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "16",
            name = "Raquel",
            lastName = "Flores",
            profileImageUrl = "https://picsum.photos/seed/16/200/200",
            bannerImageUrl = "https://picsum.photos/seed/16_banner/800/400",
            rating = 4.7f,
            isVerified = true,
            isOnline = true,
            services = listOf("Música", "Bandas en Vivo", "Clases de Baile"),
            address = "Estudio Musical El Sol",
            email = "raquel.f@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = true,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "17",
            name = "Alberto",
            lastName = "Castillo",
            profileImageUrl = "https://picsum.photos/seed/17/200/200",
            bannerImageUrl = "https://picsum.photos/seed/17_banner/800/400",
            rating = 4.2f,
            isVerified = false,
            isOnline = true,
            services = listOf("Pintura de Casas", "Diseño de Interiores", "Arquitectura"),
            address = "Calle del Color 75",
            email = "alberto.c@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/17_gallery/400/300"),
            isFavorite = false,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "18",
            name = "Marta",
            lastName = "Ortega",
            profileImageUrl = "https://picsum.photos/seed/18/200/200",
            bannerImageUrl = "https://picsum.photos/seed/18_banner/800/400",
            rating = 4.8f,
            isVerified = true,
            isOnline = true,
            services = listOf("Cuidado de Mascotas", "Paseo de Perros"),
            address = "Parque de los Amigos Caninos",
            email = "marta.o@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = false,
            works24h = true,
            galleryImages = listOf("https://picsum.photos/seed/18_gallery/400/300"),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "19",
            name = "Sergio",
            lastName = "Soto",
            profileImageUrl = "https://picsum.photos/seed/19/200/200",
            bannerImageUrl = "https://picsum.photos/seed/19_banner/800/400",
            rating = 4.3f,
            isVerified = true,
            isOnline = false,
            services = listOf("Reparación de Móviles", "Tecnología", "Soporte Técnico"),
            companyName = "PC-Soluciones",
            address = "Calle del Chip 128",
            email = "sergio.s@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = false,
            isSubscribed = false
        ),
        PrestadorProfileFalso(
            id = "20",
            name = "Silvia",
            lastName = "Reyes",
            profileImageUrl = "https://picsum.photos/seed/20/200/200",
            bannerImageUrl = "https://picsum.photos/seed/20_banner/800/400",
            rating = 4.9f,
            isVerified = true,
            isOnline = true,
            services = listOf("Traducción", "Redacción", "Consultoría"),
            address = "Oficina Global 505",
            email = "silvia.r@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = true,
            galleryImages = listOf(),
            isFavorite = true,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "21",
            name = "Roberto",
            lastName = "Vega",
            profileImageUrl = "https://picsum.photos/seed/21/200/200",
            bannerImageUrl = "https://picsum.photos/seed/21_banner/800/400",
            rating = 4.0f,
            isVerified = false,
            isOnline = false,
            services = listOf("DJ", "Sonido para Fiestas", "Iluminación para Fiestas", "Bartender"),
            companyName = "Fiesta Total",
            address = "Avenida del Ritmo 100",
            email = "roberto.v@example.com",
            doesHomeVisits = true,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf("https://picsum.photos/seed/21_gallery/400/300"),
            isFavorite = false,
            isSubscribed = true
        ),
        PrestadorProfileFalso(
            id = "22",
            name = "Patricia",
            lastName = "Nuñez",
            profileImageUrl = "https://picsum.photos/seed/22/200/200",
            bannerImageUrl = "https://picsum.photos/seed/22_banner/800/400",
            rating = 4.8f,
            isVerified = true,
            isOnline = true,
            services = listOf("Fisioterapia", "Masajes Terapéuticos", "Acupuntura"),
            address = "Centro de Bienestar Corporal",
            email = "patricia.n@example.com",
            doesHomeVisits = false,
            hasPhysicalLocation = true,
            works24h = false,
            galleryImages = listOf(),
            isFavorite = true,
            isSubscribed = false
        )
    )

    fun getPrestadorById(id: String): PrestadorProfileFalso? {
        return prestadores.find { it.id == id }
    }
}
